services:

  # Serviço PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Mapeia a porta do PostgreSQL
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./teste/app:/var/www/html/app
      - ./teste/bootstrap:/var/www/html/bootstrap
      - ./teste/config:/var/www/html/config
      - ./teste/database:/var/www/html/database
      - ./teste/public:/var/www/html/public
      - ./teste/resources:/var/www/html/resources
      - ./teste/routes:/var/www/html/routes
      - ./teste/tests:/var/www/html/tests

    depends_on:
      - db
 
    networks:
      - app

networks:
  app:
    driver: bridge
