services:

  # Serviço PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Mapeia a porta do PostgreSQL
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
 
    networks:
      - app

networks:
  app:
    driver: bridge
